#!/usr/bin/env python3
"""Generate the C++ model table from registry.yaml.

The enum and its metadata are one artifact: a model that reaches the enum has an
entry, a pinned revision, a digest and a parity verdict, or the build fails.
"""

import hashlib
import pathlib
import sys

try:
    import yaml
except ImportError:
    sys.exit("PyYAML is required: pip install -r scripts/requirements.txt")

ROOT = pathlib.Path(__file__).resolve().parent.parent
REGISTRY = ROOT / "registry.yaml"
OUTPUT = ROOT / "src" / "registry_generated.hpp"

REQUIRED = ("id", "enum", "onnx_path", "dim", "max_seq_length", "normalize")


def escape(text):
    return text.replace("\\", "\\\\").replace('"', '\\"')


def main(strict):
    raw = REGISTRY.read_text()
    version = hashlib.sha256(raw.encode()).hexdigest()[:12]
    models = yaml.safe_load(raw)["models"]

    incomplete = []
    for model in models:
        # normalize: false is a value, so only absent or empty fields count.
        missing = [field for field in REQUIRED if model.get(field) in (None, "")]
        # An unpinned model can change underneath a built index, so shipping one
        # is worse than not supporting it.
        unpinned = [f for f in ("revision", "onnx_sha256", "tokenizer_sha256", "parity")
                    if not model.get(f)]
        if missing:
            sys.exit(f"{model.get('id', '?')}: missing {', '.join(missing)}")
        if unpinned:
            incomplete.append((model["id"], unpinned))

    if incomplete and strict:
        for model_id, fields in incomplete:
            print(f"{model_id}: unpinned {', '.join(fields)}", file=sys.stderr)
        sys.exit("refusing to generate: run the pin and parity jobs first")

    lines = [
        "// Generated by scripts/gen_registry.py from registry.yaml. Do not edit.",
        "",
        "#ifndef CYBORGDB_EMBED_REGISTRY_GENERATED_HPP",
        "#define CYBORGDB_EMBED_REGISTRY_GENERATED_HPP",
        "",
        '#include "cyborgdb_embed/embed.hpp"',
        "",
        "namespace cyborgdb::embed::detail {",
        "",
        # Changes whenever any pinned value changes, which is what invalidates
        # an index built against an earlier one.
        f'inline constexpr std::string_view kRegistryVersion = "{version}";',
        "",
        "enum class Pooling { ClsToken, MeanTokens, MaxTokens };",
        "",
        "struct RegistryEntry {",
        "  ModelInfo info;",
        "  std::string_view onnx_path;",
        "  std::string_view onnx_sha256;",
        "  std::string_view tokenizer_sha256;",
        "  std::string_view query_prefix;",
        "  std::string_view doc_prefix;",
        "  Pooling pooling;",
        "};",
        "",
        "inline constexpr RegistryEntry kRegistry[] = {",
    ]

    pooling = {
        "cls_token": "Pooling::ClsToken",
        "mean_tokens": "Pooling::MeanTokens",
        "max_tokens": "Pooling::MaxTokens",
    }

    for model in models:
        lines += [
            "    {",
            f'        {{ModelId::{model["enum"]}, "{escape(model["id"])}",',
            f'         "{escape(model.get("revision") or "")}", {model["dim"]},',
            f'         {model["max_seq_length"]}, {str(model["normalize"]).lower()}}},',
            f'        "{escape(model["onnx_path"])}",',
            f'        "{escape(model.get("onnx_sha256") or "")}",',
            f'        "{escape(model.get("tokenizer_sha256") or "")}",',
            f'        "{escape(model.get("query_prefix") or "")}",',
            f'        "{escape(model.get("doc_prefix") or "")}",',
            f'        {pooling[model["pooling"]]},',
            "    },",
        ]

    # Parallel to kRegistry, so supported_models() can hand back a contiguous
    # array without copying.
    lines += ["};", "", "inline constexpr ModelInfo kModels[] = {"]
    for model in models:
        lines.append(
            f'    {{ModelId::{model["enum"]}, "{escape(model["id"])}", '
            f'"{escape(model.get("revision") or "")}", {model["dim"]}, '
            f'{model["max_seq_length"]}, {str(model["normalize"]).lower()}}},'
        )

    lines += [
        "};",
        "",
        f"inline constexpr std::size_t kModelCount = {len(models)};",
        "",
        "}  // namespace cyborgdb::embed::detail",
        "",
        "#endif  // CYBORGDB_EMBED_REGISTRY_GENERATED_HPP",
        "",
    ]

    OUTPUT.write_text("\n".join(lines))
    print(f"{OUTPUT.relative_to(ROOT)}: {len(models)} models", end="")
    print(f", {len(incomplete)} unpinned" if incomplete else "")


if __name__ == "__main__":
    main(strict="--strict" in sys.argv)
