// Generated by scripts/gen_registry.py from registry.yaml. Do not edit.

#ifndef CYBORGDB_EMBED_REGISTRY_GENERATED_HPP
#define CYBORGDB_EMBED_REGISTRY_GENERATED_HPP

#include "cyborgdb_embed/embed.hpp"

namespace cyborgdb::embed::detail {

inline constexpr std::string_view kRegistryVersion = "1321a563d85e";

enum class Pooling { ClsToken, MeanTokens, MaxTokens };

struct RegistryEntry {
  ModelInfo info;
  std::string_view onnx_path;
  std::string_view onnx_sha256;
  std::string_view tokenizer_sha256;
  std::string_view query_prefix;
  std::string_view doc_prefix;
  Pooling pooling;
};

inline constexpr RegistryEntry kRegistry[] = {
    {
        {ModelId::AllMiniLmL6V2, "sentence-transformers/all-MiniLM-L6-v2",
         "1110a243fdf4706b3f48f1d95db1a4f5529b4d41", 384,
         256, true},
        "onnx/model.onnx",
        "6fd5d72fe4589f189f8ebc006442dbb529bb7ce38f8082112682524616046452",
        "be50c3628f2bf5bb5e3a7f17b1f74611b2561a3a27eeab05e5aa30f411572037",
        "",
        "",
        Pooling::MeanTokens,
    },
    {
        {ModelId::AllMiniLmL12V2, "sentence-transformers/all-MiniLM-L12-v2",
         "a50ef00143b4d5391434df20ae11632588ac25be", 384,
         128, true},
        "onnx/model.onnx",
        "84c56795d395593cbee215e2d635a8f0ad3199ae99f99299c44cf1eaecff3ad4",
        "be50c3628f2bf5bb5e3a7f17b1f74611b2561a3a27eeab05e5aa30f411572037",
        "",
        "",
        Pooling::MeanTokens,
    },
    {
        {ModelId::AllMpnetBaseV2, "sentence-transformers/all-mpnet-base-v2",
         "e8c3b32edf5434bc2275fc9bab85f82640a19130", 768,
         384, true},
        "onnx/model.onnx",
        "74187b16d9c946fea252e120cfd7a12c5779d8b8b86838a2e4c56573c47941bd",
        "b8be2c30ba5dd723a6d5ee26d013da103d5408d92ddcb23747622f9e48f1d842",
        "",
        "",
        Pooling::MeanTokens,
    },
    {
        {ModelId::BgeSmallEnV15, "BAAI/bge-small-en-v1.5",
         "5c38ec7c405ec4b44b94cc5a9bb96e735b38267a", 384,
         512, true},
        "onnx/model.onnx",
        "828e1496d7fabb79cfa4dcd84fa38625c0d3d21da474a00f08db0f559940cf35",
        "d241a60d5e8f04cc1b2b3e9ef7a4921b27bf526d9f6050ab90f9267a1f9e5c66",
        "Represent this sentence for searching relevant passages: ",
        "",
        Pooling::ClsToken,
    },
    {
        {ModelId::BgeBaseEnV15, "BAAI/bge-base-en-v1.5",
         "a5beb1e3e68b9ab74eb54cfd186867f64f240e1a", 768,
         512, true},
        "onnx/model.onnx",
        "9bc579acdba21c253c62a9bf866891355a63ffa3442b52c8a37d75b2ccb91848",
        "d241a60d5e8f04cc1b2b3e9ef7a4921b27bf526d9f6050ab90f9267a1f9e5c66",
        "Represent this sentence for searching relevant passages: ",
        "",
        Pooling::ClsToken,
    },
    {
        {ModelId::BgeLargeEnV15, "BAAI/bge-large-en-v1.5",
         "d4aa6901d3a41ba39fb536a557fa166f842b0e09", 1024,
         512, true},
        "onnx/model.onnx",
        "69ed3f810d3b6d13f70dff9ca89966f39c0a0e877fb88211be7bcc070df2a2ce",
        "d241a60d5e8f04cc1b2b3e9ef7a4921b27bf526d9f6050ab90f9267a1f9e5c66",
        "Represent this sentence for searching relevant passages: ",
        "",
        Pooling::ClsToken,
    },
    {
        {ModelId::E5SmallV2, "intfloat/e5-small-v2",
         "ffb93f3bd4047442299a41ebb6fa998a38507c52", 384,
         512, true},
        "model.onnx",
        "4b8205be2a3c5fc53c6534d76a2012064f7309c162b806f2889c6ec8ec4fdcba",
        "d241a60d5e8f04cc1b2b3e9ef7a4921b27bf526d9f6050ab90f9267a1f9e5c66",
        "query: ",
        "passage: ",
        Pooling::MeanTokens,
    },
    {
        {ModelId::E5BaseV2, "intfloat/e5-base-v2",
         "f52bf8ec8c7124536f0efb74aca902b2995e5bcd", 768,
         512, true},
        "onnx/model.onnx",
        "157f97ef1957d34f52efa26f8031371bf9043acc45460cec7ebe94631ac0e96b",
        "d241a60d5e8f04cc1b2b3e9ef7a4921b27bf526d9f6050ab90f9267a1f9e5c66",
        "query: ",
        "passage: ",
        Pooling::MeanTokens,
    },
    {
        {ModelId::E5LargeV2, "intfloat/e5-large-v2",
         "f169b11e22de13617baa190a028a32f3493550b6", 1024,
         512, true},
        "onnx/model.onnx",
        "f560bbc5da586764fc6ccf54990bac71f94e5a872ed4e1889039391c849cbcf8",
        "d241a60d5e8f04cc1b2b3e9ef7a4921b27bf526d9f6050ab90f9267a1f9e5c66",
        "query: ",
        "passage: ",
        Pooling::MeanTokens,
    },
    {
        {ModelId::MultilingualE5Small, "intfloat/multilingual-e5-small",
         "614241f622f53c4eeff9890bdc4f31cfecc418b3", 384,
         512, true},
        "onnx/model.onnx",
        "ca456c06b3a9505ddfd9131408916dd79290368331e7d76bb621f1cba6bc8665",
        "0b44a9d7b51c3c62626640cda0e2c2f70fdacdc25bbbd68038369d14ebdf4c39",
        "query: ",
        "passage: ",
        Pooling::MeanTokens,
    },
};

inline constexpr ModelInfo kModels[] = {
    {ModelId::AllMiniLmL6V2, "sentence-transformers/all-MiniLM-L6-v2", "1110a243fdf4706b3f48f1d95db1a4f5529b4d41", 384, 256, true},
    {ModelId::AllMiniLmL12V2, "sentence-transformers/all-MiniLM-L12-v2", "a50ef00143b4d5391434df20ae11632588ac25be", 384, 128, true},
    {ModelId::AllMpnetBaseV2, "sentence-transformers/all-mpnet-base-v2", "e8c3b32edf5434bc2275fc9bab85f82640a19130", 768, 384, true},
    {ModelId::BgeSmallEnV15, "BAAI/bge-small-en-v1.5", "5c38ec7c405ec4b44b94cc5a9bb96e735b38267a", 384, 512, true},
    {ModelId::BgeBaseEnV15, "BAAI/bge-base-en-v1.5", "a5beb1e3e68b9ab74eb54cfd186867f64f240e1a", 768, 512, true},
    {ModelId::BgeLargeEnV15, "BAAI/bge-large-en-v1.5", "d4aa6901d3a41ba39fb536a557fa166f842b0e09", 1024, 512, true},
    {ModelId::E5SmallV2, "intfloat/e5-small-v2", "ffb93f3bd4047442299a41ebb6fa998a38507c52", 384, 512, true},
    {ModelId::E5BaseV2, "intfloat/e5-base-v2", "f52bf8ec8c7124536f0efb74aca902b2995e5bcd", 768, 512, true},
    {ModelId::E5LargeV2, "intfloat/e5-large-v2", "f169b11e22de13617baa190a028a32f3493550b6", 1024, 512, true},
    {ModelId::MultilingualE5Small, "intfloat/multilingual-e5-small", "614241f622f53c4eeff9890bdc4f31cfecc418b3", 384, 512, true},
};

inline constexpr std::size_t kModelCount = 10;

}  // namespace cyborgdb::embed::detail

#endif  // CYBORGDB_EMBED_REGISTRY_GENERATED_HPP
