// Generated by scripts/gen_registry.py from registry.yaml. Do not edit.

#ifndef CYBORGDB_EMBED_REGISTRY_GENERATED_HPP
#define CYBORGDB_EMBED_REGISTRY_GENERATED_HPP

#include "cyborgdb_embed/embed.hpp"

namespace cyborgdb::embed::detail {

inline constexpr std::string_view kRegistryVersion = "1fbf1b358cca";

enum class Pooling { ClsToken, MeanTokens, MaxTokens };

struct RegistryEntry {
  ModelInfo info;
  std::string_view onnx_path;
  std::string_view onnx_sha256;
  std::string_view query_prefix;
  std::string_view doc_prefix;
  Pooling pooling;
};

inline constexpr RegistryEntry kRegistry[] = {
    {
        {ModelId::AllMiniLmL6V2, "sentence-transformers/all-MiniLM-L6-v2",
         "", 384,
         256, true},
        "onnx/model.onnx",
        "",
        "",
        "",
        Pooling::MeanTokens,
    },
    {
        {ModelId::AllMiniLmL12V2, "sentence-transformers/all-MiniLM-L12-v2",
         "", 384,
         128, true},
        "onnx/model.onnx",
        "",
        "",
        "",
        Pooling::MeanTokens,
    },
    {
        {ModelId::AllMpnetBaseV2, "sentence-transformers/all-mpnet-base-v2",
         "", 768,
         384, true},
        "onnx/model.onnx",
        "",
        "",
        "",
        Pooling::MeanTokens,
    },
    {
        {ModelId::BgeSmallEnV15, "BAAI/bge-small-en-v1.5",
         "", 384,
         512, true},
        "onnx/model.onnx",
        "",
        "Represent this sentence for searching relevant passages: ",
        "",
        Pooling::ClsToken,
    },
    {
        {ModelId::BgeBaseEnV15, "BAAI/bge-base-en-v1.5",
         "", 768,
         512, true},
        "onnx/model.onnx",
        "",
        "Represent this sentence for searching relevant passages: ",
        "",
        Pooling::ClsToken,
    },
    {
        {ModelId::BgeLargeEnV15, "BAAI/bge-large-en-v1.5",
         "", 1024,
         512, true},
        "onnx/model.onnx",
        "",
        "Represent this sentence for searching relevant passages: ",
        "",
        Pooling::ClsToken,
    },
    {
        {ModelId::E5SmallV2, "intfloat/e5-small-v2",
         "", 384,
         512, true},
        "onnx/model.onnx",
        "",
        "query: ",
        "passage: ",
        Pooling::MeanTokens,
    },
    {
        {ModelId::E5BaseV2, "intfloat/e5-base-v2",
         "", 768,
         512, true},
        "onnx/model.onnx",
        "",
        "query: ",
        "passage: ",
        Pooling::MeanTokens,
    },
    {
        {ModelId::E5LargeV2, "intfloat/e5-large-v2",
         "", 1024,
         512, true},
        "onnx/model.onnx",
        "",
        "query: ",
        "passage: ",
        Pooling::MeanTokens,
    },
    {
        {ModelId::MultilingualE5Small, "intfloat/multilingual-e5-small",
         "", 384,
         512, true},
        "onnx/model.onnx",
        "",
        "query: ",
        "passage: ",
        Pooling::MeanTokens,
    },
};

inline constexpr ModelInfo kModels[] = {
    {ModelId::AllMiniLmL6V2, "sentence-transformers/all-MiniLM-L6-v2", "", 384, 256, true},
    {ModelId::AllMiniLmL12V2, "sentence-transformers/all-MiniLM-L12-v2", "", 384, 128, true},
    {ModelId::AllMpnetBaseV2, "sentence-transformers/all-mpnet-base-v2", "", 768, 384, true},
    {ModelId::BgeSmallEnV15, "BAAI/bge-small-en-v1.5", "", 384, 512, true},
    {ModelId::BgeBaseEnV15, "BAAI/bge-base-en-v1.5", "", 768, 512, true},
    {ModelId::BgeLargeEnV15, "BAAI/bge-large-en-v1.5", "", 1024, 512, true},
    {ModelId::E5SmallV2, "intfloat/e5-small-v2", "", 384, 512, true},
    {ModelId::E5BaseV2, "intfloat/e5-base-v2", "", 768, 512, true},
    {ModelId::E5LargeV2, "intfloat/e5-large-v2", "", 1024, 512, true},
    {ModelId::MultilingualE5Small, "intfloat/multilingual-e5-small", "", 384, 512, true},
};

inline constexpr std::size_t kModelCount = 10;

}  // namespace cyborgdb::embed::detail

#endif  // CYBORGDB_EMBED_REGISTRY_GENERATED_HPP
